server:
  port: 9000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/getcode
    username: root
    password: 12345678

search:
  result:
    count:
      random:
        enable: true
        min: 1000000
        max: 2000000
    result_per_page: 20
    number_of_suggestion: 12

admin:
  login:
    user: getcodeadmin
    password: zM6#U%c&gB9d4+Rb